### ISSUE TITLE
.iPA Files not being selected

### ISSUE THREAD

**Issue by bradleytechman** [powenn/ModMyIPA#25]
Upon attempting to select a .iPA file, it does not select when I tap on it.

iPhone 13 Pro
iOS 16.4
Installed with my certificate and TanaraSign
I tried multiple iPA files
Version 1.02

**Comment by almas77** [comment]
> Upon attempting to select a .iPA file, it does not select when I tap on it.
> 
> iPhone 13 Pro iOS 16.4 Installed with my certificate and TanaraSign I tried multiple iPA files Version 1.02

**Comment by bradleytechman** [comment]
Forgot to add it fixed itself once signed with TrollStore!
